config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations:'registrations' }
  resources :users
  resources :events 
  resources :invites
  resources :attendances

  root "events#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :venue, presence: true
  validates :date, presence: true
  validates :description, presence: true
  belongs_to :event_creator, class_name: "User" 
  has_many :invites, foreign_key: :invited_event_id, dependent: :destroy
  has_many :event_invitees, through: :invites
  has_many :attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :event_attendees, through: :attendances
  scope :upcoming, -> { where('date > ?', DateTime.now) }
  scope :past, -> { where('date < ?', DateTime.now) }
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :event_invitee, class_name: "User"
  belongs_to :invited_event, class_name: "Event"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :created_events, foreign_key: :event_creator_id, class_name: "Event", dependent: :destroy
  has_many :invites, foreign_key: :event_invitee_id, dependent: :destroy
  has_many :invited_events, through: :invites
  has_many :attendances, foreign_key: :event_attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    attendance = Attendance.new
    attendance.attended_event_id = params[:attended_event_id]
    attendance.event_attendee_id = params[:event_attendee_id]

    attendance.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    attendance = Attendance.find(params[:id])
    attendance.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @upcoming = Event.upcoming.includes(:event_invitees, :event_attendees, :event_creator).to_a
    @past = Event.past.includes(:event_invitees, :event_attendees, :event_creator).to_a 
  end


  def show
    @event = Event.includes(:event_creator, :event_invitees, :event_attendees).find(params[:id])
    @invitees = User.joins(:invited_events).where(:invited_events => {:name => @event.name}).to_a
    @attendees = User.joins(:attended_events).where(:attended_events => {:name => @event.name}).to_a
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    event = Event.find(params[:id])
    event.destroy
    redirect_to root_path
  end


  private
  def event_params
    params.require(:event).permit(:name, :description, :date, :venue)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  def create
    invite = Invite.new
    invite.invited_event_id = params[:invited_event_id]
    invite.event_invitee_id = params[:event_invitee_id]

    invite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    invite = Invite.find(params[:id])
    invite.destroy
    redirect_back(fallback_location: root_path)
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user).to_a
    @event = Event.find(params[:invited_event_id])
    @invitees = User.joins(:invited_events).where(:invited_events => {:name => @event.name}).to_a
    @invites = Invite.all.to_a
  end

  def show
    @user = User.find(params[:id])
    @event = Event.new
    @created_events = User.find(params[:id]).created_events.includes(:event_attendees, :event_invitees, :event_creator).to_a
    @invited_events = User.find(params[:id]).invited_events.includes(:event_attendees, :event_invitees, :event_creator).to_a

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_events.html.erb
<div class="columns is-multiline">
<% events.each do |event|%>
    <div class="column is-one-third">
      <%= link_to event do %>
        <div class="card">


        <% if user_signed_in? %>
          <% if event.event_attendees.include?(current_user) %>
            <div class="card-header has-background-primary">
          <% elsif event.event_invitees.include?(current_user) %>
            <div class="card-header has-background-warning">
          <% else %>
            <div class="card-header has-background-light">
          <% end %>
        <% else %>
          <div class="card-header has-background-light">
        <% end %>
            <p class="card-header-title is-capitalized is-size-5 is-centered">
              <%= event.name%>
            </p>
          </div>

          
        
          <div class="card-content is-size-6 has-text-weight-light has-text-justified is-clipped" style="height: 100px">
            <%= event.description %>
          </div>
          
          <div class="card-footer">
            <div class="card-footer-item">
              <%= event.date.strftime("%F")%>
            </div>
            <div class="card-footer-item has-text-centered">
              <%= event.event_creator.name %>
            </div>  
          </div>
        </div> 
      <% end %>         
    </div>
<% end %>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>
  <div id="event-form">
    <%= form.text_field :name, placeholder: 'Name' %>
    <%= form.text_field :description, placeholder: 'Description' %>
    <%= form.datetime_field :date, placeholder: ''%>
    <%= form.text_field :venue, placeholder: 'Venue' %>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <column class="is-half">
        <%= render 'form'%>
      </column>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<section class="section">
  <div class="container">
    <h2 class="is-size-2 has-text-weight-bold">
      Upcoming Events
    </h2>
    <%= render 'events', events:@upcoming %>
    <h2 class="is-size-2 has-text-weight-bold">
      Past Events
    </h2>
    <%= render 'events', events:@past %>
  </div>
</section>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half has-background-primary">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<% invite_status = @invitees.include?(current_user) %> 
<% attendance_status = @attendees.include?(current_user) %> 
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <div class="card">
          <% if user_signed_in? %>
            <% if attendance_status %>
              <div class="card-header has-background-primary">
            <% elsif invite_status %>
              <div class="card-header has-background-warning">
            <% else %>
              <div class="card-header has-background-light">
            <% end %>
          <% else %>
            <div class="card-header has-background-light">
          <% end %>
            <h2 class="card-header-title is-size-4 is-capitalized">
              <% if user_signed_in? && current_user == @event.event_creator %>
                <%= link_to edit_event_path do %>
                  <%= @event.name %>
                <% end %>
              <% else %>
                <%= @event.name %>
              <% end %>

            </h2>
          </div>

          <div class="card-content">
            <div class="content columns transform">
              <div class="column">
                <p class="is-capitalized">
                  Hosted by: <%= @event.event_creator.name %>
                </p>
                <p>
                  <%= @event.date.to_date %>
                </p>
              </div>
              <div class="column">
                <div class="dropdown is-hoverable">
                  <div class="dropdown-trigger">
                    <div class="button" style="width: 150px">
                      <span>
                        Invited: <%= @event.event_invitees.length %>
                      </span>
                      <span class="icon is-small">
                        <i class="fas fa-angle-down"></i>
                      </span>
                    </div>
                    <div class="dropdown-menu">
                      <div class="dropdown-content" style="width: 150px">
                        <% @event.event_invitees.each do |invitee| %>
                          <div class="dropdown-item">
                            <span>
                              <%= invitee.name %>
                            </span>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>

              <div class="column">
                <div class="dropdown is-hoverable">
                  <div class="dropdown-trigger">
                    <div class="button style="width: 150px">
                      <span>
                        Attending: <%= @event.event_attendees.length %>
                      </span>
                      <span class="icon is-small">
                        <i class="fas fa-angle-down"></i>
                      </span>
                    </div>
                    <div class="dropdown-menu">
                      <div class="dropdown-content" style="width: 150px">
                        <% @event.event_attendees.each do |attendee| %>
                          <div class="dropdown-item">
                            <span>
                              <%= attendee.name %>
                            </span>
                          </div>
                        <% end %>  
                      </div>
                    </div>
                  </div>
                </div>
              </div>

            </div>

            <div class="content">
              <p class="has-text-justified notification">
                <%= @event.description %>
              </p>
            </div>
          </div>

          <div class="card-footer">
            <% if user_signed_in? %>
              <% if attendance_status %>
                <% attendance = @event.attendances.select{|item| item.event_attendee_id == current_user.id} %>
                <div class="card-footer-item">
                  <p class="button is-fullwidth is-primary">
                    <%= link_to 'Cancel' , attendance_path(attendance), method: :delete %>
                  </p>
                </div>
              <% elsif invite_status %>
                <div class="card-footer-item">
                  <p class="button is-fullwidth is-primary">
                    <%= link_to 'Attend' , attendances_path(event_attendee_id: current_user.id, attended_event_id: @event.id), method: :post %>
                  </p>
                </div>
              <% end %>

              <% if current_user == @event.event_creator %>
                <div class="card-footer-item">
                  <p class="button is-fullwidth is-warning">
                    <%= link_to 'Manage Guest' , users_path(invited_event_id: @event.id) %>
                  </p>
                </div>
                <div class="card-footer-item">
                <p class="button is-fullwidth is-danger">
                  <%= link_to 'Cancel Event' , event_path, method: :delete %>
                </p>
              </div>
              <% end %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>      
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>      
    <% end %>

    <nav class="navbar has-background-black">
      <div class="navbar-brand">
        <div class="navbar-item">
          <%= link_to root_path do %>
            <h1 class="title is-3 has-text-white">Private</h1>
          <% end %>
        </div>
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample" onclick="document.querySelector('.navbar-menu').classList.toggle('is-active');">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

      <div class="navbar-menu">
        <div class="navbar-end">
          <% if user_signed_in? %>
          <div class="navbar-item">
            <%= link_to current_user.name , current_user, class: "button" %>
          </div>
          <div class="navbar-item">
            <%= link_to 'Edit User', edit_registration_path(current_user), class: "button" %>
          </div>
          <div class="navbar-item">
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "button" %>
          </div>
        <% else %> 
          <div class="navbar-item">
            <%= link_to 'Sign In', new_user_session_path, class: "button" %>
          </div>
          <div class="navbar-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "button" %>
          </div>

        <% end %>
                
        </div>
      </div>
    </nav>


  
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<style>


  input {
    border-radius: 0.5rem;
    padding: 0.5rem;
    width: 90%;
    height: 2rem;
  }

  input:focus {
      outline: none !important;
      border:1px solid red;
      box-shadow: 0 0 10px #719ECE;
    }
  }

</style>

<%= form_with model: @event do |form| %>
  <div class="columns is-centered">
    <div class="column is-half">
    <%= form.text_field :name, placeholder: 'Name' %>
    <%= form.text_field :description, placeholder: 'Description' %>
    <%= form.datetime_field :date, placeholder: ''%>
    <%= form.text_field :venue, placeholder: 'Venue' %>
    <%= form.submit %>
    </div>
<% end %>

app/views/users/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="card column is-half">
        <div class="card-header">
          <div class="card-header-title has-background-danger is-centered is-size-4">
            Guest List
          </div>
        </div>
        <div class="card-content">

          <% @users.each do |user|%>
            <% status = @invitees.include?(user) %>

            <div class="columns notification">
              <div class="column is-one-third">
                <%= user.name %>
              </div>
              <div class="column is-one-third">
                <% if status %>
                <p class="has-text-primary">invited</p>
                <% end %>
              </div>
              <% if status %>
                <div class="column is-one-third">
                  <% invite = @invites.select{|item| item.event_invitee_id == user.id} %>
                  <%= link_to invite_path(invite), method: :delete, class: "button" do %>
                    <p style="width: 100px">uninvite</p>
                  <% end %>
                </div>
              <% else %>
                <div class="column is-one-third">
                  <%= link_to invites_path(event_invitee_id: user.id, invited_event_id: @event.id), method: :post, class: "button" do %>
                    <p style="width: 100px">invite</p>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>   
        </div> 
        
        <div class="card-footer">
          <%= link_to @event ,class: "button is-fullwidth is-primary" do %>
            <p class="is-size-4 has-text-black">Back</p>
          <% end %>            
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns" >
      <div class="column" style="align-self: flex-start">
        <h2 class="is-size-2 has-text-weight-bold">
          Create Events
        </h2>
        <%= render 'events/form' %>
      </div>
      <div class="column">
        <h2 class="is-size-2 has-text-weight-bold">
          Organized Events
        </h2>
        <%= render 'events/events', events: @created_events %>

        <h2 class="is-size-2 has-text-weight-bold">
          Invited Events
        </h2>
        <%= render 'events/events', events: @invited_events %>
      </div>
    </div>
  </div>
</section>